### PR TITLE
Migrate the legacy examples to the Merlin repo

### PR DESCRIPTION
**Pull request by karlhigley**
We may (or may not) want to keep these examples but they've overstayed their welcome in the NVTabular repo, which is burdened with the accumulation of a lot of historical cruft. Since some of these examples use inference code that's moving to Systems, it makes more sense for them to live in the Merlin repo (if we want to keep them.)

The PR on the other side of this migration is https://github.com/NVIDIA-Merlin/NVTabular/pull/1711

### CODE REVIEW

**Comment by jperez999** [comment]
> @jperez999 In order for this to work, I think the Jenkins tests for this repo would need access to the datasets we store on a mounted drive?

yes this is true, but they already exist on the jenkins machine. Your failures seem to have to do with not finding the actual files to run.

**Comment by bschifferer** [comment]
@karlhigley can we add the README from NVTabular to the legacy folder?

**Comment by bschifferer** [comment]
@karlhigley can we merge the PR?

**Comment by bschifferer** [comment]
rerun tests

**Pull request merged**
