### PR TITLE
docs: semver to calver banner

### PR DESCRIPTION
**Pull request by mikemckiernan**

### CODE REVIEW

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Review by EvenOldridge — APPROVED** [review]
This looks good.  I'm assuming the Jenkins error is unrelated?

**Comment by mikemckiernan** [comment]
rerun tests

**Pull request merged**
