### PR TITLE
Remove hugectr inference

### PR DESCRIPTION
**Pull request by EmmaQiaoCh**
Remove hugectr inference backend;
Add installation of hps_torch in merlin-torch.

### CODE REVIEW

**Comment by bashimao** [comment]
Do we really want to remove that?

**Comment by EmmaQiaoCh** [comment]
> Do we really want to remove that?

Yes, I checked with Yingcan. Could you review it again^^

**Comment by EmmaQiaoCh** [comment]
The copied PR is merged

**Pull request closed without merging**
