### PR TITLE
Pin pyarrow version for integration tests

### PR DESCRIPTION
**Pull request by oliverholworthy**
Pin pyarrow version for integration tests.

The `pip install 'feast<0.20'` command is installing the latest version of pyarrow (currently 10.0.1). This is incompatibile with the current version of cudf. 

## Follow-up

The container we're testing with already has pyarrow installed. So a follow-up action would be to figure out why the existing pyarrow version is not being detected and take any actions required for this to be found.

- `import pyarrow; pyarrow.__version__` reports 8.0.0. 
  - However, `pip show pyarrow` doesn't report anything. 
  - Suggesting that the pyarrow installation is incomplete (missing [the dist-info directory](https://packaging.python.org/en/latest/specifications/recording-installed-packages/#the-dist-info-directory))

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by jperez999** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
This error about no such file while trying to save the merlin schema when the model is saved is because [keras uses the tf.io in-memory filesystem which I think is a tensorflow io feature (I've not seen `ram://` used outside of this context at least) when trying to pickle a model](https://github.com/keras-team/keras/blob/v2.10.0/keras/saving/pickle_utils.py#L62). And to use this RAM filesystem, you can't use regular python file io functionality it seems. We'll need to use tf.io functions to write things into this in-memory filesystem. 

This looks like it's [been replaced in TF 2.11 by a regular regular temporary directory on disk](https://github.com/keras-team/keras/commit/2ed044d06d0ae552477672aa8b778f8edafb52f1). However, since we currently aim to support versions back to TF 2.8, will need to handle both cases now.

The reason this has only appeared now? Until recently we weren't testing the ability to pickle a TF Merlin Model.   The recent change in systems to use the executor triggered this to be checked now https://github.com/NVIDIA-Merlin/systems/pull/255 since it relies on cloudpickle to save the model artifact.

**Comment by oliverholworthy** [comment]
This PR on models https://github.com/NVIDIA-Merlin/models/pull/930 should fix the error we're getting from the notebook test when trying to serialize the model

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Pull request merged**
