### PR TITLE
add dataloader unit testing to container run

### PR DESCRIPTION
**Pull request by jperez999**
Adds an entry to run unit tests from dataloader repo in the ci script.

### CODE REVIEW

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
notebook test is timing out. Increasing limit from 2 mins to 3 mins seems to work #729 not sure why it's got slower though (and maybe worth a follow-up to check. might be the code, but might also be the environment?). Perhaps we were close to the limit before. 

Based on this PR, it does seem like we're now consistently not able to run within the previous time limit.

**Review by oliverholworthy — APPROVED** [review]

**Comment by jperez999** [comment]
rerun tests

**Pull request merged**
