### PR TITLE
docs: Readability improvements

### PR DESCRIPTION
**Pull request by ryanrussell**
Readability fixes in the examples. One small fix in the readme.

### CODE REVIEW

**Review by benfred — APPROVED** [review]

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Pull request merged**
