### PR TITLE
[Ready to be reviewed] Support Customized HCTR Repo in the unified containers

### PR DESCRIPTION
**Pull request by zehuanw**
Design point: 
* New added arguments are fully compatible with all the existing ci scripts, the behavior will not be changed with the default values.
* Support HugeCTR Development in containers by ARG HUGECTR_DEV_MODE
* Support the configuration to _HUGECTR_REPO / _HUGECTR_BRANCH / _HUGECTR_BACKEND_BRANCH / _HUGECTR_BACKEND_REPO

Arguments supported:

HugeCTR will not be installed when HUGECTR_DEV_MODE=true
ARG HUGECTR_DEV_MODE=false

Arguments "_XXXX" are only valid when $HUGECTR_DEV_MODE==false
ARG _HUGECTR_BRANCH=master
ARG _HUGECTR_REPO="github.com/NVIDIA-Merlin/HugeCTR.git"
ARG _HUGECTR_BACKEND_BRANCH=main
ARG _HUGECTR_BACKEND_REPO="github.com/triton-inference-server/hugectr_backend"
ARG _CI_JOB_TOKEN=""

### CODE REVIEW

**Review by benfred — COMMENTED** [review]
Thanks for making these changes @zehuanw !  

@albert17 can you verify that this works with the build before we merge?

**Comment by zehuanw** [comment]
We disabled "ARROW_ORC" temporally in this MR because of some related errors in the nightly unified container building. Per @shijieliu those errors also exist in the main branch on NVIDIA-Merlin and he has communicated with @albert17.

**Comment by albert17** [comment]
@zehuanw Please resolve conflicts since containers have been updated to 22.01 release

**Comment by shijieliu** [comment]
@albert17 @benfred conflicts have been resolved. Please varify

**Review by albert17 — APPROVED** [review]

**Pull request merged**
