### PR TITLE
Raw id notebook Conversion how to

### PR DESCRIPTION
**Pull request by jperez999**
In this PR, I show how it is possible to store the raw id for both items and users in the feature store and use those ids where necessary within the pipeline.

### CODE REVIEW

**Comment by viswa-nvidia** [comment]
realted to https://github.com/NVIDIA-Merlin/Merlin/issues/458

**Comment by nv-alaiacano** [comment]
It's hard to review a notebook, but in your cell with

```python
top_k=10
ordering = combined_features["item_id"] >> SoftmaxSampling(
    relevance_col=ranking["click/binary_classification_task"], topk=top_k, temperature=20.0
)
```

You can replace `item_id` with `item_id_raw` since it's already in your `FeatureView`. This will produce the final ordered version of the "raw" item ids and remove the need for the final `QueryFeast`

```python
top_k=10
ordering = combined_features["item_id_raw"] >> SoftmaxSampling(
    relevance_col=ranking["click/binary_classification_task"], topk=top_k, temperature=20.0
)
```

**Comment by rnyak** [comment]
> It's hard to review a notebook, but in your cell with
> 
> ```python
> top_k=10
> ordering = combined_features["item_id"] >> SoftmaxSampling(
>     relevance_col=ranking["click/binary_classification_task"], topk=top_k, temperature=20.0
> )
> ```
> 
> You can replace `item_id` with `item_id_raw` since it's already in your `FeatureView`. This will produce the final ordered version of the "raw" item ids and remove the need for the final `QueryFeast`
> 
> ```python
> top_k=10
> ordering = combined_features["item_id_raw"] >> SoftmaxSampling(
>     relevance_col=ranking["click/binary_classification_task"], topk=top_k, temperature=20.0
> )
> ```

@nv-alaiacano thanks for the comment. I am actually gonna close this PR and create a new one. I already modified the example notebooks around this PR,  and used `ordering = combined_features["item_id_raw"] ` as you and @karlhigley pointed out. But the issue is unit test fails on CI. You can check the  CI error in this PR as well.  https://github.com/NVIDIA-Merlin/Merlin/pull/487

**Comment by nv-alaiacano** [comment]
>            assert outputs[0] == "ordered_ids"
> E           AssertionError: assert 'item_category' == 'ordered_ids'
> E             - ordered_ids
> E             + item_category

Make sure you're running against the latest `main` branch of systems. I made a change in systems to _not_ rename the output column to `ordered_ids`, and instead keep the name of the column that is actually being ordered (in this case, `item_category`). It ultimately got reverted for unrelated reasons, but it seems like you might be running a test against a version of systems while it was in there.

**Comment by rnyak** [comment]
closing this, since we have another PR https://github.com/NVIDIA-Merlin/Merlin/pull/618

**Pull request closed without merging**
