### PR TITLE
Update multi-stage deployment notebooks and integration test

### PR DESCRIPTION
**Pull request by rnyak**
I get the following error from TIS when I send a request in the integration test:

```
E0921 20:42:17.777335328   16250 server_chttp2.cc:40]        {"created":"@1663792937.777314949","description":"Only 1 addresses added out of total 2 resolved","file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":403,"referenced_errors":[{"created":"@1663792937.777312476","description":"Address family not supported by protocol","errno":97,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":395,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::1]:8001"}]}
I0921 20:42:17.777789 16250 grpc_server.cc:4587] Started GRPCInferenceService at localhost:8001
I0921 20:42:17.778444 16250 http_server.cc:3303] Started HTTPService at 0.0.0.0:8000
I0921 20:42:17.820455 16250 http_server.cc:178] Started Metrics Service at 0.0.0.0:8002
0921 20:42:22.556590 16354 pb_stub.cc:776] Failed to process the request(s) for model '0_queryfeast', message: TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. c_python_backend_utils.InferenceResponse(output_tensors: List[c_python_backend_utils.Tensor], error: c_python_backend_utils.TritonError = None)

Invoked with: kwargs: tensors=[], error="<class 'TypeError'>, int() argument must be a string, a bytes-like object or a number, not 'NoneType', [<FrameSummary file /tmp/examples/poc_ensemble/0_queryfeast/1/model.py, line 105 in execute>, <FrameSummary file /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/op_runner.py, line 54 in execute>, <FrameSummary file /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/ops/feast.py, line 309 in transform>]"

At:
  /tmp/examples/poc_ensemble/0_queryfeast/1/model.py(122): execute
```

### CODE REVIEW

**Comment by rnyak** [comment]
@nv-alaiacano I wonder if the error above occurs bcs the raw dataset has rows where user_id_raw and item_id_raw are NANs? Can this somehow being a problem for QueryFeast  or QueryFaiss ops when we send request with `user_id_raw`?

**Comment by bschifferer** [comment]
rerun tests

**Comment by bschifferer** [comment]
rerun tests

**Review by oliverholworthy — APPROVED** [review]
I checked out this PR and the integration test and notebooks run successfully with the synthetic data for me.

**Comment by oliverholworthy** [comment]
Merged, since this has fixed the main error we were seeing that was stopping the notebook from running. However, if there is still an issue with the real dataset on the CI machine (w.r.t. NAN values) we can address this in another PR.

**Pull request merged**
